language: java
jdk: oraclejdk9
services:
  - docker
matrix:
  include:
    - jdk: openjdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
script:
  - mvn install
  - cd mock_notification_service
  - mvn clean install
  - cd ../
  - docker-compose up -d --build
  - docker-compose down
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.host.url=http://sonar.galles.io