language: java
jdk: oraclejdk9
services:
  - docker
matrix:
  include:
    - jdk: openjdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
notifications:
  slack: informatiquep-kyw7477:lC8s8YdlUaOFLThMaw7UGben
script:
  - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=WARN
  - mvn install -q -B -Dorg.slf4j.simpleLogger.defaultLogLevel=warn
  - cd mock_notification_service
  - mvn clean install -q -B -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN
  - cd ../
  - cd dronemock
  - mvn clean install -q -B -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN
  - cd ../
  - docker-compose up -d --build
  - docker-compose down
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.host.url=http://sonar.galles.io-q -B -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN