version: '3'
services:
  warehouse-server:
    container_name: dronazone-warehouse-server
    build:
      context: warehouse
      dockerfile: DOCKERFILE
      args:
        JAR_FILE: target/wharehouse-0.0.1-SNAPSHOT.jar
    image: dronazone-warehouse-server:latest
    expose:
      - 8081
    ports:
      - 8081:8080
    networks:
      - dronazone-network
    logging:
      driver: json-file
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      DATASOURCE_HOST: postgres
      NOTIFICATION_HOST: notification

  drone-server:
    container_name: dronazone-drone-server
    build:
      context: drone
      dockerfile: DOCKERFILE
      args:
        JAR_FILE: target/drone-0.0.1-SNAPSHOT.jar
    image: dronazone-drone-server:latest
    expose:
      - 8082
    ports:
      - 8082:8080
    networks:
      - dronazone-network
    logging:
      driver: json-file
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres-dronazone
    image: postgres
    environment:
      POSTGRES_PASSWORD: dronazone
      POSTGRES_USER: dronazone
      POSTGRES_DB: dronazone
    ports:
      - 5432:5432
    networks:
      - dronazone-network
  notification:
    container_name: dronazone-notification-mock-server
    build:
      context: mock_notification_service
      dockerfile: DOCKERFILE
      args:
        JAR_FILE: target/mock_notification_service-0.0.1-SNAPSHOT.jar
    image: dronizone-mock-notification
    expose:
      - 8080
    ports:
      - 44444:8080
    networks:
      - dronazone-network
    logging:
      driver: json-file

networks:
  dronazone-network:
    driver: bridge
