# This file is used to document the queries made in the scenario
############should not be expected that this file is up to date######################
###Pinging the servers
#Order
GET http://localhost:8082
#Warehouse
###
GET http://locahost:8081
#### Ordering and item
POST http://localhost:8082/order
Content-Type: application/json

{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "orderItem",
  "params": {
    "order": {
      "coord": {
        "lat": 48,
        "lon": 7.5
      },
      "item": {
        "name": "Item1"
      },
      "customer": {
        "name": "Roger",
        "firstName": "Roger"
      },
      "paymentInfo": "pay_in_illicit_material"
    }
  }
}

###
#### listing orders to be paid
GET http://localhost:8081/warehouse/orders

###
#### Setting orders ready for delivery
PUT http://localhost:8081/warehouse/orders/2

###
GET http://localhost:8084/commands/debug/commands

###
GET http://localhost:44444/notifications/mock/notification_history

#### Changing the notificaiton media
POST http://localhost:8082/order
Content-Type: application/json

{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "setPersonalPreferences",
  "params": {
    "customerId": 2,
    "notificationPreference": "SMS"
  }
}

###
POST http://localhost:8083/drone/fleet/command/callback


###