spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dronazone
    username: postgres
    password: azerty
  batch:
    initialize-schema: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

