spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST}:5432/dronazone
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PWD}
  batch:
    initialize-schema: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test_group
      group-id: order-service
