spring:
  datasource:
#    url: jdbc:postgresql://${DATASOURCE_HOST}:5432/dronazone
    url: jdbc:postgresql://${DATASOURCE_HOST}:9001/dronazone
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PWD}
  batch:
    initialize-schema: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092
    consumer:
      group-id: order-service