spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: dronazone
    password: dronazone
  batch:
    initialize-schema: always
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092
    consumer:
      group-id: order-service