
spring:

  datasource:
    url: jdbc:h2:mem:testdb
    username: dronazone
    password: dronazone
  batch:
    initialize-schema: always
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    consumer:
      group-id: drone-service
      enable-auto-commit: true
server:
  port: 8083