spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST}:5432/dronazone
    username: dronazone
    password: dronazone
  batch:
    initialize-schema: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092
    consumer:
      group-id: drone-service